name: Feature Request / 功能请求
description: 'Submit a Feature Request / 提交一个功能请求'
labels: [enhancement]
body:
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type / 功能类型
      description: |
        Which type does this feature belong to? This helps developers plan and categorize it.  
        该功能属于以下哪种类型，便于开发者计划分类。
      options:
        - 'In-Game / 游戏内'
        - 'Launcher Appearance / 启动器外观'
        - 'Launcher Settings / 启动器设置'
        - 'New Feature / 新功能'
        - 'Feature Enhancement / 功能补充'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description / 详细描述
      description: |
        Clearly and thoroughly describe your feature request.  
        清晰，详细地描述出您的功能请求。
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos / 截图或视频
      description: |
        If necessary, you can upload screenshots or videos.  
        必要的话，您可以上传截图、视频。
    validations:
      required: false
